baseURL = "https://sukalaper.github.io"
locale = "id"
title = "Sukalaper Blog"
theme = "kissstyle"
publishDir = "docs"

[markup]
  [markup.highlight]
    noClasses = true
    style = "modus-vivendi"  
    lineNos = true    

[params]
description = "Technical Blog and Portfolio"